version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-develop
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:5.0.8
    container_name: redis-develop
    ports:
      - 6379:6379

  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper-develop
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka-develop
    ports:
      - 9092:9092
      - 49092:49092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: FROMDOCKER://:49092,LOCAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: FROMDOCKER:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: FROMDOCKER://host.docker.internal:49092,LOCAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: topic-test:1:1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    container_name: elasticsearch-develop
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.1
    container_name: kibana-develop
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes:
  mysql-data:
  es-data:
